### PR TITLE
Replace Spanish suffixes by Portuguese suffixes in the Portuguese snowba...

### PR DESCRIPTION
**Pull request by he7d3r**
...ll stemmer

As in https://github.com/nltk/nltk/issues/754.

### CODE REVIEW

**Comment by ojwb** [comment]
This changes the results of stemming the test vocabulary (for example `devolução` now stems to `devolu` rather than `devoluçã`) - have you reviewed those changes to confirm they all make sense?

**Comment by he7d3r** [comment]
Yep!

**Comment by ojwb** [comment]
Hi @he7d3r

I'm trying to tidy up the licensing situation for snowball (see snowballstem/snowball#10 for more details).

Are you OK to license this patch and the patch in #2 under the 3-clause BSD licence shown here:

http://opensource.org/licenses/BSD-3-Clause

**Comment by he7d3r** [comment]
Sure!

**Pull request merged**
